apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wordpress-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c18785b9d063eed2::fsap-0675f1814e4ac4913
